from task_8 import (SimpleGraph)
from task_8_2 import (DirectedGraph, CheckDirGraph)
SimpleGraph.DirectedGraph = DirectedGraph
SimpleGraph.CheckDirGraph = CheckDirGraph
# тест: вершина имеется, связи с ней отсутствуют# 
graph = SimpleGraph(5)
print(graph.AddVertex(10), end=" ")
print(graph.AddVertex(20), end=" ")
print(graph.vertex[0].Value, end=" ")
print(graph.vertex[1].Value, end=" ")
print(graph.IsEdge(0, 1), end=" ")
print(graph.IsEdge(0, 2), end=" ")
print(graph.IsEdge(1, 2))
# тест: до добавления связи между вершинами не было, после добавления появилась
graph = SimpleGraph(5)
graph.AddVertex(10)
graph.AddVertex(20)
print(graph.IsEdge(0, 1), end=" ")
graph.AddEdge(0, 1)
print(graph.IsEdge(0, 1), end=" ")
print(graph.m_adjacency[0][1], end=" ")
print(graph.m_adjacency[1][0])
# тест: до удаления связь между вершинами была, после удаления отсутствует
graph = SimpleGraph(5)
graph.AddVertex(10)
graph.AddVertex(20)
graph.AddEdge(0, 1)
print(graph.IsEdge(0, 1), end=" ")
graph.RemoveEdge(0, 1)
print(graph.IsEdge(0, 1), end=" ")
print(graph.m_adjacency[0][1], end=" ")
print(graph.m_adjacency[1][0])
# тест: до удаления некоторые вершины имеют связи с удаляемой вершиной, после удаления этих связей нету
graph = SimpleGraph(5)
graph.AddVertex(100)
graph.AddVertex(200)
graph.AddVertex(300)
graph.AddEdge(0, 1)
graph.AddEdge(0, 2)
graph.AddEdge(1, 2)
print(graph.IsEdge(0, 1), end=" ")
print(graph.IsEdge(0, 2), end=" ")
print(graph.IsEdge(1, 2), end=" ")
graph.RemoveVertex(0)
print(graph.vertex[0], end=" ")
print(graph.IsEdge(0, 1), end=" ")
print(graph.IsEdge(0, 2), end=" ")
print(graph.IsEdge(1, 2), end=" ")
print(graph.m_adjacency[0][1], end=" ")
print(graph.m_adjacency[0][2])
# тест 2* направленный граф
graph = SimpleGraph(5)
graph.AddVertex(1)
graph.AddVertex(2)
graph.AddVertex(3)
graph.AddVertex(4)
graph.AddVertex(5)
graph.AddEdge(0, 1)
graph.AddEdge(1, 2)
graph.AddEdge(0, 2)
graph.AddEdge(2, 3)
graph.AddEdge(3, 4)
weak = graph.DirectedGraph()
print(len(weak), end=" ")
print(weak[0].Value, end=" ")
print(weak[1].Value)