# task 10 *4
set1 = PowerSet()
set1.put(1)
set1.put(2)
set2 = PowerSet()
set2.put('a')
set2.put('b')
set2.put('c')
result_1 = cartesian(set1, set2)
print(result_1)
set3 = PowerSet()
set3.put(1)
set3.put(2)
result_2 = cartesian(set3)
print(result_2)