# main_quest:
# полный кэш и вытеснение
cache = NativeCache(3)
cache.put("key_aa", "значение_1")
cache.put("key_bb", "значение_2")
cache.put("key_cc", "значение_3")
print(cache.slots)
print(all(slot is not None for slot in cache.slots))
cache.get_key("key_aa")
cache.get_key("key_aa")
cache.get_key("key_bb")
print(cache.get_hits("key_aa"))
print(cache.get_hits("key_bb"))
print(cache.get_hits("key_cc"))
cache.put("key_dd", "значение_4")
print(cache.slots)
print(cache.values)
print(cache.hits)
print(cache.cash_key("key_aa"))
print(cache.cash_key("key_bb"))
print(cache.cash_key("key_cc"))
print(cache.cash_key("key_dd"))
print()
# подсчет количества обращений к ключам
cache2 = NativeCache(2)
cache2.put("ключ_1", "значение_1")
cache2.put("ключ_2", "значение_2")
print(cache2.get_hits("ключ_1"))
print(cache2.get_hits("ключ_2"))
cache2.get_key("ключ_1")
cache2.get_key("ключ_1")
cache2.get_key("ключ_2")
print(cache2.get_hits("ключ_1"))
print(cache2.get_hits("ключ_2"))
print(cache2.get_hits("несуществующий"))
print()
# Много коллизий
cache3 = NativeCache(4)
cache3.put("key_ab", "значение_1")
cache3.put("key_ef", "значение_2")
cache3.put("key_cd", "значение_3")
cache3.put("key_gh", "значение_4")
print(cache3.slots)
print(cache3.hits)
cache3.get_key("key_ab")
cache3.get_key("key_ab")
cache3.get_key("key_ef")
cache3.get_key("key_cd")
print(cache3.hits)
cache3.put("key_ij", "новое значение")
print(cache3.slots)
print(cache3.hits)
print(cache3.cash_key("key_ab"))
print(cache3.cash_key("key_ef"))
print(cache3.cash_key("key_cd"))
print(cache3.cash_key("key_gh"))
print(cache3.cash_key("key_ij"))


# task 10 *4
set1 = PowerSet()
set1.put(1)
set1.put(2)
set2 = PowerSet()
set2.put('a')
set2.put('b')
set2.put('c')
result_1 = cartesian(set1, set2)
print(result_1)
set3 = PowerSet()
set3.put(1)
set3.put(2)
result_2 = cartesian(set3)
print(result_2)

# task 11-2 *3
bloom_filter_1 = BloomFilter3(f_len=32)
bloom_filter_1.add('1')
bloom_filter_1.add('2')
bloom_filter_1.add('3')
print(bloom_filter_1.is_value('1'))
print(bloom_filter_1.is_value('2'))
print(bloom_filter_1.is_value('3'))
print(bloom_filter_1.is_value('4')) # False
bloom_filter_1.remove('1')
print(bloom_filter_1.is_value('1')) # False
print(bloom_filter_1.is_value('2'))
bloom_filter_1.add('1')
print(bloom_filter_1.is_value('1')) # True